luizalabs_panel/luizalabs_panel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('panel/', include('panel.urls')),
]

luizalabs_panel/panel/urls.py
from django.urls import path

from . import views

app_name = 'panel'

urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
    path('', views.loginIndex, name='loginIndex'),
    path('login', views.login, name='login'),
    path('api/login', views.loginApi, name='loginApi'),
    
#     path('getemployee/<str:employee_id>/', views.getEmployee, name='getEmployee'),
    path('getemployeelist', views.getEmployeeList, name='getEmployeeList'),
    
    path('api/addedituser', views.addEditUserApi, name='addEditUserApi'),
    
    path('api/getemployee/<str:employee_id>/', views.getEmployeeApi, name='getEmployeeApi'),
    path('api/getemployeelist/', views.getEmployeeListApi, name='getEmployeeListApi'),
    path('api/addeditemployee/', views.addEditEmployeeApi, name='addEditEmployeeApi'),
    path('api/removeemployee/<str:employee_id>/', views.removeEmployeeApi, name='removeEmployeeApi'),
]

luizalabs_panel/panel/models.py
from django.db import models

# Create your models here.

luizalabs_panel/panel/views.py
from django.http import HttpResponse
import pymongo
import json
import logging
from django.shortcuts import render
from bson.objectid import ObjectId
import traceback
from datetime import datetime
import os
import binascii
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import redirect

connection = pymongo.MongoClient('127.0.0.1', 27017) # LOCAL / PROD

db = connection["PanelApp"]

User = db['User']
Employee = db['Employee']
Token = db['Token']

commonFields = ['created', 'updated']
userFields = ['name', 'email', 'username', 'password', 'enabled', 'user_type']+commonFields
employeeFields = ['name', 'email', 'departament']+commonFields
tokenFields = ['user_id', 'user_type']+commonFields

#user_type
user_admin_type = 0
user_manager_type = 1

#VerifyRequest
def verifyRequest(required):
    def decorator(func):
        def wrapper(*args, **kwargs):
            request = args[0]
            logging.info("Request: "+str(request))
            if 'photo' in request.FILES or request.method == 'DELETE':
                dictionary = request.GET.dict()
            elif request.method == 'POST' or request.method == 'PUT':
                dictionary = request.POST.dict()
                try:
                    postDict = json.loads(request.body)
                    dictionary.update(postDict)
                except:
                    pass
                
                try:
                    getDict = request.GET.dict()
                    dictionary.update(getDict)
                except:
                    pass
                    
            elif request.method == 'GET' or request.method == 'DELETE':
                dictionary = request.GET.dict()
                
            args += (dictionary,)

            for i in required:
                if i == 'token':
                    if 'HTTP_AUTHORIZATION' not in request.META:
                        if 'token' not in dictionary:
                            return makeResponse(False, data={}, error="Parameter not found: token")
                        else:
                            token = dictionary['token']
                    else:
                        token = request.META['HTTP_AUTHORIZATION']
                        dictionary['token'] = token

                    
                    tokenDB = Token.find_one({'_id' : token})
                    if tokenDB == None:
                        return makeResponse(False, data={}, error="Token not found!")
                    else:
                        requested_by = User.find_one({"$and" : [{'_id' : ObjectId(tokenDB['user_id'])}, {'enabled' : True}]})
                        if requested_by == None:
                            return makeResponse(False, data={}, error="Admin not found.")
                        args += (requested_by,)
                elif i not in dictionary:
                    printDict(dictionary.copy())
                    return makeResponse(False, data={}, error ="Parameter not found: " + i)
                
            printDict(dictionary.copy())
            return func(*args, **kwargs)
        return wrapper
    return decorator

def printDict(dictionary):
#Censura informações sensíveis do dictionary para registro do log
    try:
        blackList = ['password']
        for field in dictionary:
            if field in blackList:
                dictionary[field] = u'*********'
                 
        logging.info("dictionary: "+str(dictionary))
    except Exception as e:
        logging.error(e)
        logging.info("dictionary: "+str(dictionary))

def makeResponse(ok, **kwargs):
    response = {}
    response['ok'] = ok
    for i in kwargs:
        response[i] = kwargs[i]
    
    if 'data' not in response:
        response['data'] = {}    
    if 'error' not in response:
        response['error'] = ''
    if 'error_list' not in response:
        response['error_list'] = []
    return json.dumps(response)

def JSONResponse(func):
    def wrapper(*args, **kwargs):
        response = func(*args, **kwargs)
        responseDict = json.loads(response)
        if 'status' in responseDict:
            return HttpResponse(response, content_type = "application/json;charset=utf-8", status = int(responseDict['status']))
        else:
            return HttpResponse(response, content_type = "application/json;charset=utf-8")
    return wrapper

def CreateToken(user_id, user_type):
    token = {
        '_id' : (binascii.b2a_hex(os.urandom(20))).decode('ascii'),
        'user_id' : str(user_id),    
        'user_type' : user_type,
        'created' : datetime.now(),
    }
    Token.save(token)
    return token['_id']

def ReturnUserToken(token):
    try:
        tokenDB = Token.find_one({'_id' : token})
        if tokenDB == None:
            return redirect('panel:loginIndex')
        
        user = User.find_one({"$and" : [{'_id' : ObjectId(tokenDB['user_id'])}, {'enabled' : True}]})
        if user == None:
            return redirect('panel:loginIndex')
           
        user.update({
            'created' : str(user['created']),
            'updated' : str(user['updated']),
            '_id' : str(user['_id']),
            'user_id' : str(user['_id']),
            'token' : token
        })
        user.pop('password', None)
        return user
    except Exception as e:
        logging.error(e)
        return redirect('panel:loginIndex')
    
def loginIndex(request):
    if User.find({}).count() == 0:
        user = {
            'name': 'Luke Skywalker',
            'username': 'luke',
            'password': '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4',
            'email': 'luke@gmail.com',
            'enabled': True,
            'user_type': 0,
            'created': datetime.now(),
            'updated': datetime.now()
        }
        User.save(user)
        request.session['session_error'] = 'Default user created. Please use username:luke/pass:1234'
        
        
    if 'session_error' in request.session and request.session['session_error']:
        context = {
            'login_data' : {
                'ok' : False,
                'error' : 'Session expired.',
                'error_list' : [request.session['session_error']]
            }
        }
        return render(request, 'panel/login.html', context)
    else:
        request.session['session_error'] = False
        return render(request, 'panel/login.html')

def dashboard(request):
    if 'token' not in request.session:
        request.session['session_error'] = True
        return redirect('panel:loginIndex')
    user = ReturnUserToken(request.session['token'])
    context = {
        'user_data': user,
    }
    return render(request, 'panel/index.html', context)

@verifyRequest(['username', 'password'])
def login(request, dictionary):
    try:
        login = LoginPrivate(dictionary)
        if login['ok']:
            request.session['token'] = login['data']['token']
            return redirect('panel:dashboard')
        else:
            context = {
                'login_data': login
            }
            return render(request, 'panel/login.html', context)        
    except Exception as e:
        logging.error(e)
        logging.info("dictionary: "+str(dictionary))
        return makeResponse(False, data={}, error='Something strange happened.')


@csrf_exempt 
@JSONResponse
@verifyRequest(['username', 'password'])
def loginApi(request, dictionary):
    try:
        login = LoginPrivate(dictionary)
        if login['ok']:
            return makeResponse(True, data=login['data'])
        else:
            return makeResponse(False, data=login['data'], error=login['error'], error_list=login['error_list'])
    except Exception as e:
        logging.error(e)
        logging.info("dictionary: "+str(dictionary))
        return makeResponse(False, data={}, error='Something strange happened.')

def LoginPrivate(dictionary):
    try:
        errors = []
        if dictionary['username'] in ['', None]:
            errors.append('Username is empty.')
        if dictionary['password'] in ['', None]:
            errors.append('Password is empty.')
        
        if errors != []:
            return {'ok' : False, 'data' : {}, 'error': '', 'error_list': errors}
        
        user = User.find_one({ '$and':[
                {'username' : {"$regex" : dictionary['username'].replace(' ', ''), "$options" : "-i"}},
                {'password' : dictionary['password']},
                {'enabled' : True}
            ]
        })
        
        if user == None:
            return {'ok' : False, 'data' : {}, 'error': 'Invalid username or password.', 'error_list':[]}
        else:
            if 'token' not in dictionary:
                token = CreateToken(str(user['_id']), user['user_type'])
            else:
                token = dictionary
                
            user.update({
                'created' : str(user['created']),
                'updated' : str(user['updated']),
                '_id' : str(user['_id']),
                'user_id' : str(user['_id']),
                'token' : str(token)
            })
            user.pop('password', None)
            return {'ok' : True, 'data' : user, 'error': '', 'error_list':[]}
    except Exception as e:
        logging.error(e)
        logging.info("dictionary: "+str(dictionary))
        return {'ok' : False, 'data' : {}, 'error': 'Something strange happened.', 'error_list':[]}
    
    
@csrf_exempt
@JSONResponse
@verifyRequest(['token', 'name', 'email', 'username', 'password', 'user_type'])
def addEditUserApi(request, dictionary, user):
    try:
        errors = []
        if dictionary['name'] in ['', None]:
            errors.append('Name is empty.')
        if dictionary['username'] in ['', None]:
            errors.append('Username is empty.')
        if dictionary['email'] in ['', None]:
            errors.append('Email is empty.')
        if dictionary['password'] in ['', None]:

luizalabs_panel/panel/templates/panel/index.html
{% extends 'panel/_layouts/base.html' %}
{% block content %}
<h1 class="page-header">Quick Access</h1>
            <div class="row">
                <div class="col-xs-6 col-sm-4 col-md-4 col-lg-2">
                    <a href="{% url 'panel:getEmployeeList' %}">
                        <div class="btn btn-lg btn-success" >
                            <h1><span class="fa fa-sign-in"></span></h1>
                            <span>List Employees</span>
                        </div>
                    </a>
                </div>
            </div>
{% endblock %}

luizalabs_panel/panel/templates/panel/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <meta name="author" content="Marcos Maia">
        <meta name="description" content="Panel App">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <title>Test - Admin Panel</title>

        <link rel="stylesheet" type="text/css" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static '/fontawesome/css/font-awesome.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static '/css/dashboard.css' %}">
        <!-- Google Fonts -->
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic,700italic|Montserrat:400,700">
    </head>
    <body>
        <section id="form" class="form-section transparent" data-type="background" data-parallax="yes">
            <div class="overlay section-padding" style="background: white;">
                <div class="container">
                    <h1 class="section-title text-center text-uppercase"><span> Admin Panel</span> Login</h1>
                    <!-- /.section-description -->
                    <div class="top-padding-50"></div>
                    <!-- /.col-md-8 -->
                    <div class="col-md-8 col-md-offset-2 col-sm-12">
                        <div class="form-container">
                            <form id="login" method="post" action="{% url 'panel:login' %}" class="login-form">{% csrf_token %}
                                <div id="msg">
                                {% if not login_data.ok %}
                                    <span class="text-danger"><center>{{ login_data.error }}</center></span>
                                {% for error in login_data.error_list %}
                                    <span class="text-danger"><center>{{ error }}</center></span>
                                {% endfor %}
                                {% endif %}
                                </div>
                                <div class="form-group">
                                    <label for="login">Username</label>
                                    <input type="text" class="form-control" id="username" name="username" placeholder="Username" required />
                                </div>

                                <div class="form-group">
                                    <label for="senha">Password</label>
                                    <input type="password" class="form-control" id="pass" name="pass" placeholder="*******" required />
                                    <input type="hidden" id="password" name="password"/>
                                </div>
                                <button type="button" id="loginButton" class="btn btn-default btn-lg"> <span class="fa fa-sign-in"></span> Log in</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <script type="text/javascript" src="{% static '/jquery/jquery.js' %}"></script>
        <script type="text/javascript" src="{% static '/js/core.js' %}"></script>
        <script type="text/javascript" src="{% static '/bootstrap/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static '/js/sha256.js' %}"></script>
        <script type="text/javascript" src="{% static '/js/dashboard.js' %}"></script>
        <script type="text/javascript">
            $('#loginButton').on('click', login);
            
            function login(e){
                var password = $('#pass').val();
                var username = $("#username").val();
                username = username.replace(" ", "")
                
                if(username == "" || password == ""){
                    $('#msg').html('<span class="text-danger"><center>Username and Password can not be empty.</center></span>');
                    return false;
                } else {
                    $('#msg').html('');
                }
                
                var hash = CryptoJS.SHA256(password);
                var pass = hash.toString();
                $('#password').val(pass);
                $('#pass').val('');
                $('#login').submit();
            }
        </script>
    </body>
</html>