luizalabs_panel/luizalabs_panel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('panel/', include('panel.urls')),
]

luizalabs_panel/panel/urls.py
from django.urls import path

from . import views

app_name = 'panel'

urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
    path('', views.loginIndex, name='loginIndex'),
    path('login', views.login, name='login'),
    path('api/login', views.loginApi, name='loginApi'),
    
#     path('getemployee/<str:employee_id>/', views.getEmployee, name='getEmployee'),
    path('getemployeelist', views.getEmployeeList, name='getEmployeeList'),
    
    path('api/addedituser', views.addEditUserApi, name='addEditUserApi'),
    
    path('api/getemployee/<str:employee_id>/', views.getEmployeeApi, name='getEmployeeApi'),
    path('api/getemployeelist/', views.getEmployeeListApi, name='getEmployeeListApi'),
    path('api/addeditemployee/', views.addEditEmployeeApi, name='addEditEmployeeApi'),
    path('api/removeemployee/<str:employee_id>/', views.removeEmployeeApi, name='removeEmployeeApi'),
]

luizalabs_panel/panel/models.py
from django.db import models

# Create your models here.

luizalabs_panel/panel/views.py
from django.http import HttpResponse
import pymongo
import json
import logging
from django.shortcuts import render
from bson.objectid import ObjectId
import traceback
from datetime import datetime
import os
import binascii
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import redirect

connection = pymongo.MongoClient('127.0.0.1', 27017) # LOCAL / PROD

db = connection["PanelApp"]

User = db['User']
Employee = db['Employee']
Token = db['Token']

commonFields = ['created', 'updated']
userFields = ['name', 'email', 'username', 'password', 'enabled', 'user_type']+commonFields
employeeFields = ['name', 'email', 'departament']+commonFields
tokenFields = ['user_id', 'user_type']+commonFields

#user_type
user_admin_type = 0
user_manager_type = 1

#VerifyRequest
def verifyRequest(required):
    def decorator(func):
        def wrapper(*args, **kwargs):
            request = args[0]
            logging.info("Request: "+str(request))
            if 'photo' in request.FILES or request.method == 'DELETE':
                dictionary = request.GET.dict()
            elif request.method == 'POST' or request.method == 'PUT':
                dictionary = request.POST.dict()
                try:
                    postDict = json.loads(request.body)
                    dictionary.update(postDict)
                except:
                    pass
                
                try:
                    getDict = request.GET.dict()
                    dictionary.update(getDict)
                except:
                    pass
                    
            elif request.method == 'GET' or request.method == 'DELETE':
                dictionary = request.GET.dict()
                
            args += (dictionary,)

            for i in required:
                if i == 'token':
                    if 'HTTP_AUTHORIZATION' not in request.META:
                        if 'token' not in dictionary:
                            return makeResponse(False, data={}, error="Parameter not found: token")
                        else:
                            token = dictionary['token']
                    else:
                        token = request.META['HTTP_AUTHORIZATION']
                        dictionary['token'] = token

                    
                    tokenDB = Token.find_one({'_id' : token})
                    if tokenDB == None:
                        return makeResponse(False, data={}, error="Token not found!")
                    else:
                        requested_by = User.find_one({"$and" : [{'_id' : ObjectId(tokenDB['user_id'])}, {'enabled' : True}]})
                        if requested_by == None:
                            return makeResponse(False, data={}, error="Admin not found.")
                        args += (requested_by,)
                elif i not in dictionary:
                    printDict(dictionary.copy())
                    return makeResponse(False, data={}, error ="Parameter not found: " + i)
                
            printDict(dictionary.copy())
            return func(*args, **kwargs)
        return wrapper
    return decorator

def printDict(dictionary):
#Censura informações sensíveis do dictionary para registro do log
    try:
        blackList = ['password']
        for field in dictionary:
            if field in blackList:
                dictionary[field] = u'*********'
                 
        logging.info("dictionary: "+str(dictionary))
    except Exception as e:
        logging.error(e)
        logging.info("dictionary: "+str(dictionary))

def makeResponse(ok, **kwargs):
    response = {}
    response['ok'] = ok
    for i in kwargs:
        response[i] = kwargs[i]
    
    if 'data' not in response:
        response['data'] = {}    
    if 'error' not in response:
        response['error'] = ''
    if 'error_list' not in response:
        response['error_list'] = []
    return json.dumps(response)

def JSONResponse(func):
    def wrapper(*args, **kwargs):
        response = func(*args, **kwargs)
        responseDict = json.loads(response)
        if 'status' in responseDict:
            return HttpResponse(response, content_type = "application/json;charset=utf-8", status = int(responseDict['status']))
        else:
            return HttpResponse(response, content_type = "application/json;charset=utf-8")
    return wrapper

def CreateToken(user_id, user_type):
    token = {
        '_id' : (binascii.b2a_hex(os.urandom(20))).decode('ascii'),
        'user_id' : str(user_id),    
        'user_type' : user_type,
        'created' : datetime.now(),
    }
    Token.save(token)
    return token['_id']

def ReturnUserToken(token):
    try:
        tokenDB = Token.find_one({'_id' : token})
        if tokenDB == None:
            return redirect('panel:loginIndex')
        
        user = User.find_one({"$and" : [{'_id' : ObjectId(tokenDB['user_id'])}, {'enabled' : True}]})
        if user == None:
            return redirect('panel:loginIndex')
           
        user.update({
            'created' : str(user['created']),
            'updated' : str(user['updated']),
            '_id' : str(user['_id']),
            'user_id' : str(user['_id']),
            'token' : token
        })
        user.pop('password', None)
        return user
    except Exception as e:
        logging.error(e)
        return redirect('panel:loginIndex')
    
def loginIndex(request):
    if User.find({}).count() == 0:
        user = {
            'name': 'Luke Skywalker',
            'username': 'luke',
            'password': '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4',
            'email': 'luke@gmail.com',
            'enabled': True,
            'user_type': 0,
            'created': datetime.now(),
            'updated': datetime.now()
        }
        User.save(user)
        request.session['session_error'] = 'Default user created. Please use username:luke/pass:1234'
        
        
    if 'session_error' in request.session and request.session['session_error']:
        context = {
            'login_data' : {
                'ok' : False,
                'error' : 'Session expired.',
                'error_list' : [request.session['session_error']]
            }
        }
        return render(request, 'panel/login.html', context)
    else:
        request.session['session_error'] = False
        return render(request, 'panel/login.html')

def dashboard(request):
    if 'token' not in request.session:
        request.session['session_error'] = True
        return redirect('panel:loginIndex')
    user = ReturnUserToken(request.session['token'])
    context = {
        'user_data': user,
    }
    return render(request, 'panel/index.html', context)

@verifyRequest(['username', 'password'])
def login(request, dictionary):
    try:
        login = LoginPrivate(dictionary)
        if login['ok']:
            request.session['token'] = login['data']['token']
            return redirect('panel:dashboard')
        else:
            context = {
                'login_data': login
            }
            return render(request, 'panel/login.html', context)        
    except Exception as e:
        logging.error(e)
        logging.info("dictionary: "+str(dictionary))
        return makeResponse(False, data={}, error='Something strange happened.')


@csrf_exempt 
@JSONResponse
@verifyRequest(['username', 'password'])
def loginApi(request, dictionary):
    try:
        login = LoginPrivate(dictionary)
        if login['ok']:
            return makeResponse(True, data=login['data'])
        else:
            return makeResponse(False, data=login['data'], error=login['error'], error_list=login['error_list'])
    except Exception as e:
        logging.error(e)
        logging.info("dictionary: "+str(dictionary))
        return makeResponse(False, data={}, error='Something strange happened.')

def LoginPrivate(dictionary):
    try:
        errors = []
        if dictionary['username'] in ['', None]:
            errors.append('Username is empty.')
        if dictionary['password'] in ['', None]:
            errors.append('Password is empty.')
        
        if errors != []:
            return {'ok' : False, 'data' : {}, 'error': '', 'error_list': errors}
        
        user = User.find_one({ '$and':[
                {'username' : {"$regex" : dictionary['username'].replace(' ', ''), "$options" : "-i"}},
                {'password' : dictionary['password']},
                {'enabled' : True}
            ]
        })
        
        if user == None:
            return {'ok' : False, 'data' : {}, 'error': 'Invalid username or password.', 'error_list':[]}
        else:
            if 'token' not in dictionary:
                token = CreateToken(str(user['_id']), user['user_type'])
            else:
                token = dictionary
                
            user.update({
                'created' : str(user['created']),
                'updated' : str(user['updated']),
                '_id' : str(user['_id']),
                'user_id' : str(user['_id']),
                'token' : str(token)
            })
            user.pop('password', None)
            return {'ok' : True, 'data' : user, 'error': '', 'error_list':[]}
    except Exception as e:
        logging.error(e)
        logging.info("dictionary: "+str(dictionary))
        return {'ok' : False, 'data' : {}, 'error': 'Something strange happened.', 'error_list':[]}
    
    
@csrf_exempt
@JSONResponse
@verifyRequest(['token', 'name', 'email', 'username', 'password', 'user_type'])
def addEditUserApi(request, dictionary, user):
    try:
        errors = []
        if dictionary['name'] in ['', None]:
            errors.append('Name is empty.')
        if dictionary['username'] in ['', None]:
            errors.append('Username is empty.')
        if dictionary['email'] in ['', None]:
            errors.append('Email is empty.')
        if dictionary['password'] in ['', None]:

luizalabs_panel/panel/templates/panel/employee/index.html
<ul>
    <li><a href="/panel/getemployeelist">Employee List</a></li>
    <li><a href="/panel/addeditemployeelist">Create Employee</a></li>
</ul>

luizalabs_panel/panel/templates/panel/employee/list.html
{% extends 'panel/_layouts/base.html' %}
{% block content %}

<div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document" style="width:400px;" >
        <div style="background-color:white;">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modalDeleteLabel">Atenção</h4>
            </div>
            <div class="modal-body" id="modalDeleteText">
            </div>
            <div id="confirmaStatus" class="modal-footer">
                <a href="#" id="modalDeleteButton" class="btn btn-danger" data-dismiss="modal">Sim</a>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Não</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="employee_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <form id="employee_form" action="" class="form-horizontal" role="form" method="post">
        {% csrf_token %}
        <input type="hidden" name="token" value="{{ user_data.token }}">
        <input type="hidden" name="employee_id" id="employee_id" value="">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">New Employee</h4>
                </div>
                <div class="modal-body">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                                <label class="control-label" for="name">Name</label>
                                <div class="input-control text" data-role="input-control">
                                    <input class="form-control" type="text" id="name" name="name">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                                <label class="control-label" for="email">Email</label>
                                <div class="input-control text" data-role="input-control">
                                    <input class="form-control" type="text" id="email" name="email">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                                <label class="control-label" for="departament">Departament</label>
                                <div class="input-control text" data-role="input-control">
                                    <input class="form-control" type="text" id="departament" name="departament">
                                </div>
                            </div>
                        </div>
                        <div id="msg">
                        </div>
                    </div>
                    <br>
                </div>
                <div class="modal-footer">
                    <button type="submit" id="saveButton" class="btn btn-primary">
                        Save
                    </button>
                    <button type="button" id="closeModal" class="btn btn-default" data-dismiss="modal">
                        Close
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
        
<div class="row">
    <div class="col-xs-6 col-sm-4 col-md-4 col-lg-2">
        <a href="#" data-toggle="modal" data-target="#employee_modal">
            <div class="btn btn-lg btn-success" >
                <h1><span class="fa fa-sign-in"></span></h1>
                <span>New Employee</span>
            </div>
        </a>
    </div>
</div>
<h3 class="sub-header">Employee List</h3>
<div class="row">
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Departament</th>
                    <th>Created</th>
                    <th>#</th>
                </tr>
            </thead>
            <tbody>
                {% if employee_list.ok %}
                    {% for employee in employee_list.data %}
                        <tr>
                            <td>{{ employee.name }}</td>
                            <td>{{ employee.email }}</td>
                            <td>{{ employee.departament }}</td>
                            <td>{{ employee.created }}</td>
                            <td>
                                <a class="blue editButton" href="#" data-id="{{ employee.employee_id }}">
                                    <i class="ace-icon fa fa-search-plus bigger-130"></i>
                                </a>
                                
                                <a class="red delbutton" href="#" data-id="{{ employee.employee_id }}" data-name="{{ employee.name }}" data-toggle="modal" data-target="#modalDelete" >
                                    <i class="ace-icon fa fa-trash-o bigger-130"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
    $(window).ready(function () {
        loadingInit();
    });
    
    $(document).on('click', '.delbutton', function(){
        delButtonModal($(this));
    });
    
    $(document).on('click', '.editButton', function(){
        find($(this).data('id'))
    });
    
    $('#employee_form').on('submit', save);
    
    function find(employee_id){
        $.ajax({
            type: 'GET',
            url: 'api/getemployee/'+employee_id,
            beforeSend: function (xhr) {
                xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
            },
            success: function (response) {
                try {
                    console.log(response);
                    if(typeof response !== 'object'){
                        response = jQuery.parseJSON(response);
                    }
                    if(response.ok){
                        $('#name').val(response.data.name)
                        $('#email').val(response.data.email)
                        $('#departament').val(response.data.departament)
                        $('#employee_id').val(response.data.employee_id)
                        $('#employee_modal').modal('show');
                    } else {
                        alert(response.error)
                    }
                    loadingHide();
                } catch(err) {
                    alert('Something strange happened, please try again.')
                    console.log(err);
                    console.log(err.responseText);
                    loadingHide();
                }
            },
            error: function(xhr, status, error){
                alert('Something strange happened, please reload and try again.')
                console.log(xhr);
                console.log(status);
                console.log(error);
                loadingHide();
            }
        });
    }
    
    function save(e){
        e.preventDefault();
        loadingShow();
        $('#msg').html('');
        var data = new FormData(e.target);
        $.ajax({
            type: 'POST',
            url: '{% url 'panel:addEditEmployeeApi' %}',
            data: data,
            contentType: false,
            processData: false,
            success: function (response) {
                try {
                    console.log(response);
                    if(typeof response !== 'object'){
                        response = jQuery.parseJSON(response);
                    }
                    if(response.ok){
                        window.location.reload();
                    } else {
                        var error = '';
                        error += '<span class="text-danger"><center>'+response.error+'</center></span>';
                        $('#msg').html(error);
                    }
                    loadingHide();
                } catch(err) {
                    var error = '';
                    error += '<span class="text-danger"><center>Something strange happened, please try again.</center></span>';
                    $('#msg').html(error);
                    console.log(err);
                    console.log(err.responseText);
                    loadingHide();
                }
            },
            error: function(xhr, status, error){
                var error = '';
                error += '<span class="text-danger"><center>Something strange happened, please reload and try again.</center></span>';
                $('#msg').html(error);
                console.log(xhr);
                console.log(status);
                console.log(error);
                loadingHide();
            }
        });
    }
    
    function delButtonModal(button){
        $('#modalDeleteText').html('Really delete ' + button.data('name') + '?');
        $('#modalDeleteButton').attr('onclick', 'remove("'+button.data('id')+'")');
        $('#modalDelete').toggle();
    }
    
    function remove(id) {
        $.ajax({
            type: 'DELETE',
            url: 'api/removeemployee/'+id,
            beforeSend: function (xhr) {
                xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
            },
            success: function (data) {
                try {
                    console.log(response);
                    if(typeof response !== 'object'){
                        response = jQuery.parseJSON(response);
                    }
                    if(response.ok){
                        window.location.reload();
                    } else {
                        var error = '';
                        error += '<span class="text-danger"><center>'+response.error+'</center></span>';
                        $('#msg').html(error);
                    }
                    loadingHide();
                } catch(err) {
                    var error = '';
                    error += '<span class="text-danger"><center>Something strange happened, please try again.</center></span>';
                    $('#msg').html(error);
                    console.log(err);
                    console.log(err.responseText);
                    loadingHide();
                }
            },
            error: function(xhr, status, error){
                var error = '';
                error += '<span class="text-danger"><center>Something strange happened, please reload and try again.</center></span>';
                $('#msg').html(error);
                console.log(xhr);
                console.log(status);
                console.log(error);
                loadingHide();
            }
        });
    }
    
</script>
{% endblock %}